Kraków/Magazyn/config/routes.rb
Rails.application.routes.draw do
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'products#index'
  get '/content' => 'products#content'
end

Kraków/Magazyn/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Kraków/Magazyn/app/models/product.rb
class Product < ApplicationRecord
end

Kraków/Magazyn/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Kraków/Magazyn/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def content
    #@file = File.open(Dir.pwd+"/storage/product.csv", "r")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:symbol, :name, :active, :author_id, :producer_id, :publication_date_id)
    end
end

Kraków/Magazyn/app/helpers/application_helper.rb
module ApplicationHelper
end

Kraków/Magazyn/app/helpers/products_helper.rb
module ProductsHelper
end

Kraków/Magazyn/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magazyn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          <h1>MAGAZYN</h1>
        </a>
        <div class="navbar-burger burger" data-target="navigation">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
  
      <div id="navigation" class="navbar-menu">
        <!--<div class="navbar-start">
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link is-active">Wpisy</a>
            <div class="navbar-dropdown">
              <a class="navbar-item" href="/topics">Tematy</a>
              <a class="navbar-item" href="/issues">Zagadnienia</a>
              <a class="navbar-item" href="/articles">Artykuły</a>
            </div>
          </div>
        </div>-->
        <a class="navbar-item" href="/">Produkty</a>
        <a class="navbar-item" href="/content">Zawartość</a>
  
        <div class="navbar-end">
          <%= form_tag products_path, class: "navbar-item", :method => 'get' do %>
            <div class="field is-grouped" style="height: 26px;">
              <%= text_field_tag :search, params[:search], placeholder: "Szukaj", class: "input" %>
              <%= submit_tag "Search", :name => nil, class: "button" %>
            </div>
          <% end %>
  
          <%= link_to "Nowy Produkt", new_product_path, class: "navbar-item" %>
        </div>
      </div>
    </nav>
  
    <div id="wrapper" class="container is-fluid">
      <% if !flash[:notice].blank? %>
        <div class="alert alert-success" style="text-align: center;">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <%= yield %>
      
    </div>
  
    <footer>
      <p><a href="http://mushix.eu/cv" target="_blank">MushiX</a> &copy; wszelkie prawa zastrzeżone</p>
      <p id="clock"></p>
    </footer>
  
    <%= javascript_include_tag 'bulma' %>
    <%= javascript_include_tag 'clock' %>
  
  </body>
  </html>

Kraków/Magazyn/app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.number_field :symbol %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.number_field :author_id %>
  </div>

  <div class="field">
    <%= form.label :producer_id %>
    <%= form.number_field :producer_id %>
  </div>

  <div class="field">
    <%= form.label :publication_date_id %>
    <%= form.number_field :publication_date_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Kraków/Magazyn/app/views/products/content.html.erb
<h2>Zawartość pliku</h2>

<table class="table is-striped is-fullwidth">
  <tbody>
    <% File.open(Dir.pwd+"/storage/product.csv", "r") do |f| %>
      <% f.each_line do |line| %>
        <tr>
          <td><%= line[0, line.index(';')] %></td>
          <% line = line[line.index(';')+1..-1] %>
          <td><%= line[0, line.index(';')] %></td>
          <% line = line[line.index(';')+1..-1] %>
          <td><%= line[0, line.index(';')] %></td>
          <% line = line[line.index(';')+1..-1] %>
          <td><%= line[0, line.index(';')] %></td>
          <% line = line[line.index(';')+1..-1] %>
          <td><%= line[0, line.index(';')] %></td>
          <% line = line[line.index(';')+1..-1] %>
          <td><%= line %></td>
          <td></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<style>
footer { position: relative; }
</style>

Kraków/Magazyn/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

Kraków/Magazyn/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<form class="columns">
  <div class="column is-4"><label>Imię</label><input type="text" class="input is-3"/></div>
  <div class="column is-4"><label>Nr Telefonu</label><input type="number" class="input is-3"/></div>
  <div class="column is-4"><label>Email</label><input type="email" class="input is-3"/></div>
</form>

<h2>Products</h2>

<table class="table is-striped is-fullwidth">
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Name</th>
      <th>Active</th>
      <th>Author</th>
      <th>Producer</th>
      <th>Publication date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <!--<td><%= product.symbol %></td>
        <td><%= product.name %></td>
        <td><%= product.active %></td>
        <td><%= product.author_id %></td>
        <td><%= product.producer_id %></td>
        <td><%= product.publication_date_id %></td>-->
        <td><%= product.name %></td>
        <td><%= product.value %></td>
        <td></td>
        <td></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path, class: "button is-fullwidth" %>

Kraków/Magazyn/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

Kraków/Magazyn/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Symbol:</strong>
  <%= @product.symbol %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @product.active %>
</p>

<p>
  <strong>Author:</strong>
  <%= @product.author_id %>
</p>

<p>
  <strong>Producer:</strong>
  <%= @product.producer_id %>
</p>

<p>
  <strong>Publication date:</strong>
  <%= @product.publication_date_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>